### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by codzofrosh** [liruoteng/HeavyRainRemoval#20]
I ran python test.py and i get the following error 
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100% 528M/528M [00:07<00:00, 76.0MB/s]
/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/model.py:342: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias, 0)
initialize network with normal
Load GAN: ... 
HeavyRain-stage2-2019-05-11-76
Traceback (most recent call last):
  File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/test.py", line 223, in <module>
    tester.predict_real()
  File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/test.py", line 55, in predict_real
    self.load_gan(self.pretrained_weights, False)
  File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/Base.py", line 276, in load_gan
    ckpt = torch.load(ckpt_path,map_location=torch.device('cuda'))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1256, in _legacy_load
    result = unpickler.load()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte

**Comment by Dovisya** [comment]
> I ran python test.py and i get the following error /usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead. warnings.warn( /usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth 100% 528M/528M [00:07<00:00, 76.0MB/s] /content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/model.py:342: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_. init.constant(m.bias, 0) initialize network with normal Load GAN: ... HeavyRain-stage2-2019-05-11-76 Traceback (most recent call last): File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/test.py", line 223, in tester.predict_real() File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/test.py", line 55, in predict_real self.load_gan(self.pretrained_weights, False) File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/Base.py", line 276, in load_gan ckpt = torch.load(ckpt_path,map_location=torch.device('cuda')) File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1256, in _legacy_load result = unpickler.load() UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte

**Comment by Dovisya** [comment]
> I ran python test.py and i get the following error /usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead. warnings.warn( /usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth 100% 528M/528M [00:07<00:00, 76.0MB/s] /content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/model.py:342: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_. init.constant(m.bias, 0) initialize network with normal Load GAN: ... HeavyRain-stage2-2019-05-11-76 Traceback (most recent call last): File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/test.py", line 223, in tester.predict_real() File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/test.py", line 55, in predict_real self.load_gan(self.pretrained_weights, False) File "/content/drive/MyDrive/ColabNotebooks/HeavyRainRemoval-master/HeavyRainRemoval-master/Base.py", line 276, in load_gan ckpt = torch.load(ckpt_path,map_location=torch.device('cuda')) File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1256, in _legacy_load result = unpickler.load() UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte

I encountered the same problem. Have you solved it?

**Comment by supersonicMaclaurin** [comment]
I encountered the same problem. Have you solved it?

**Comment by 15101051** [comment]
`torch.load(ckpt_path,map_location=torch.device('cuda'), encoding='latin1')` works for me.
